---
title: "classification"
output: html_notebook
---

##LOAD
```{r}
library(quantmod)
library(finreportr)
library(edgar)
library(BatchGetSymbols)
library(lubridate)
library(dplyr)

library(pdftools)
library(glue)
library(tidyverse)

library(caret)

library(mice)

library(randomForest)
require(caTools)

library(MLmetrics)
```


## Data Clean
```{r}

ipos.df = read.csv("MT IPO DATA_with_market_final.csv")

ipos.df$Net.Income.Margin = ipos.df$Net.Income / ipos.df$Total.Revenues.Last.Reported
ipos.df$OneDayChange = ipos.df$FirstDayClose/ipos.df$Offer.Price -1
ipos.df$LogOneDayChange = log(ipos.df$FirstDayClose/ipos.df$Offer.Price)
ipos.df$RevGrowth = ipos.df$Total.Revenues.Last.Reported/ipos.df$Total.Revenues.in.Previous.Year-1
ipos.df$Long.Term.Debt.to.Total.Asset.Ratio = ipos.df$Long.Term.Debt/ipos.df$Total.Assets
ipos.df$Total.VC.Funding.Raised = as.numeric(ipos.df$Total.VC.Funding.Raised)/1000


ipos.df = ipos.df %>%
  filter(Ticker.Symbol != "UBER") %>%
  filter(Ticker.Symbol != "FB") %>%
  filter(Ticker.Symbol != "GRPN") %>%
  filter(Ticker.Symbol != "LYFT") 

ipos = ipos.df %>% 
  dplyr::select(LogOneDayChange, VIX_before, market_performance,Total.VC.Funding.Raised, Total.Revenues.Last.Reported, Total.Assets,Long.Term.Debt, Long.Term.Debt.to.Total.Asset.Ratio, Selling.and.Marketing, Total.Operating.Expenses, Net.Income, Net.Income.Margin, Type.of.Security, Investment.Bank..Lead.Left., Additional.Lead.Underwriters, RevGrowth, Proceeds)

miceIPO <- mice(ipos, method="rf")  # perform mice imputation, based on random forests.
miceOutput <- complete(miceIPO)  # generate the completed data.

ipos.clean = miceOutput

ipos.clean$Underpriced = ifelse(ipos.clean$LogOneDayChange >0.1823 , 1,0)


```


##Logistic Regression Confusion for Underpriced 0.2
```{r}
set.seed(123)
trainIndex <- createDataPartition(ipos.clean$Underpriced, p = .8, 
                                  list = FALSE, 
                                  times = 1)

train = ipos.clean[trainIndex,]
train = train %>%
  dplyr::select(-LogOneDayChange)
test = ipos.clean[-trainIndex,]
test = test %>%
  dplyr::select(-LogOneDayChange)


  

logit.model_0.2 = glm(data = train, formula = Underpriced ~ VIX_before + market_performance  + Selling.and.Marketing + Net.Income.Margin + RevGrowth + Total.Assets + log(Proceeds) + Type.of.Security  + Selling.and.Marketing:RevGrowth + market_performance:Selling.and.Marketing, family=binomial(link='logit'))

pdata_log <- predict(logit.model_0.2, newdata = test, type = "response")

confusionMatrix(data = as.factor(as.numeric(pdata_log>0.5)), reference = as.factor(test$Underpriced))

summary(logit.model_0.2)

#ROC Curve
simple_roc <- function(labels, scores){
  labels <- labels[order(scores, decreasing=TRUE)]
  data.frame(TPR=cumsum(labels)/sum(labels), FPR=cumsum(!labels)/sum(!labels), labels)
}

#CV
ipos_cv<-ipos.clean[sample(nrow(ipos.clean)),]
folds<-cut(seq(1,nrow(ipos.clean)),breaks=10,labels=FALSE)
test_list<-list()
train_list<-list()
for(i in 1:10){
  test_indices<-which(folds==i,arr.ind=TRUE)
  ipos_test<-ipos_cv[test_indices,]
  test_list[[i]]<-ipos_test
  ipos_train<-ipos_cv[-test_indices,]
  train_list[[i]]<-ipos_train
}

logit.model_0.2_auc = c()
for(i in 1:10){
  logit.model_0.2_cv = glm(data = train_list[[i]], formula = Underpriced ~ VIX_before + market_performance  + Selling.and.Marketing + Net.Income.Margin + RevGrowth + Total.Assets + log(Proceeds) + Type.of.Security  + Selling.and.Marketing:RevGrowth + market_performance:Selling.and.Marketing, family=binomial(link='logit'))
  
  y_pred = predict(logit.model_0.2_cv, newdata = test_list[[i]], type = "response")
  y_pred = as.numeric(y_pred>0.5)
  y_true = test_list[[i]]$Underpriced
  logit.model_0.2_auc  = AUC(y_pred = y_pred, y_true = y_true)
}
test_auc_0.2<-c(mean(logit.model_0.2_auc))
test_auc_0.2



```


##Logistic Regression Confusion for Underpriced 0.1
```{r}
set.seed(123)
ipos.clean$Underpriced = ifelse(ipos.clean$LogOneDayChange >0.0953 , 1,0)
trainIndex <- createDataPartition(ipos.clean$Underpriced, p = .8, 
                                  list = FALSE, 
                                  times = 1)

train = ipos.clean[trainIndex,]
train = train %>%
  dplyr::select(-LogOneDayChange)
test = ipos.clean[-trainIndex,]
test = test %>%
  dplyr::select(-LogOneDayChange)

logit.model_0.1 = glm(data = train, formula = Underpriced ~ VIX_before + market_performance  + Selling.and.Marketing + Net.Income.Margin + RevGrowth + Total.Assets + log(Proceeds) + Type.of.Security  + Selling.and.Marketing:RevGrowth + market_performance:Selling.and.Marketing, family=binomial(link='logit'))

pdata_log <- predict(logit.model_0.1, newdata = test, type = "response")

confusionMatrix(data = as.factor(as.numeric(pdata_log>0.5)), reference = as.factor(test$Underpriced))


#CV
ipos_cv<-ipos.clean[sample(nrow(ipos.clean)),]
folds<-cut(seq(1,nrow(ipos.clean)),breaks=10,labels=FALSE)
test_list<-list()
train_list<-list()
for(i in 1:10){
  test_indices<-which(folds==i,arr.ind=TRUE)
  ipos_test<-ipos_cv[test_indices,]
  test_list[[i]]<-ipos_test
  ipos_train<-ipos_cv[-test_indices,]
  train_list[[i]]<-ipos_train
}

logit.model_0.1_auc = c()
for(i in 1:10){
  logit.model_0.1_cv = glm(data = train_list[[i]], formula = Underpriced ~ VIX_before + market_performance  + Selling.and.Marketing + Net.Income.Margin + RevGrowth + Total.Assets + log(Proceeds) + Type.of.Security  + Selling.and.Marketing:RevGrowth + market_performance:Selling.and.Marketing, family=binomial(link='logit'))
  
  y_pred = predict(logit.model_0.1_cv, newdata = test_list[[i]], type = "response")
  y_pred = as.numeric(y_pred>0.5)
  y_true = test_list[[i]]$Underpriced
  logit.model_0.1_auc  = AUC(y_pred = y_pred, y_true = y_true)
}
test_auc_0.1<-c(mean(logit.model_0.1_auc))
test_auc_0.1

```

##Logistic Regression Confusion for Underpriced 0
```{r}
set.seed(123)
ipos.clean$Underpriced = ifelse(ipos.clean$LogOneDayChange >0 , 1,0)
trainIndex <- createDataPartition(ipos.clean$Underpriced, p = .8, 
                                  list = FALSE, 
                                  times = 1)

train = ipos.clean[trainIndex,]
train = train %>%
  dplyr::select(-LogOneDayChange)
test = ipos.clean[-trainIndex,]
test = test %>%
  dplyr::select(-LogOneDayChange)

logit.model_0 = glm(data = train, formula = Underpriced ~ VIX_before + market_performance  + Selling.and.Marketing + Net.Income.Margin + RevGrowth + Total.Assets + log(Proceeds) + Type.of.Security  + Selling.and.Marketing:RevGrowth + market_performance:Selling.and.Marketing, family=binomial(link='logit'))

pdata_log <- predict(logit.model_0, newdata = test, type = "response")

confusionMatrix(data = as.factor(as.numeric(pdata_log>0.5)), reference = as.factor(test$Underpriced))

#CV
ipos_cv<-ipos.clean[sample(nrow(ipos.clean)),]
folds<-cut(seq(1,nrow(ipos.clean)),breaks=10,labels=FALSE)
test_list<-list()
train_list<-list()
for(i in 1:10){
  test_indices<-which(folds==i,arr.ind=TRUE)
  ipos_test<-ipos_cv[test_indices,]
  test_list[[i]]<-ipos_test
  ipos_train<-ipos_cv[-test_indices,]
  train_list[[i]]<-ipos_train
}

logit.model_0_auc = c()
for(i in 1:10){
  logit.model_0_cv = glm(data = train_list[[i]], formula = Underpriced ~ VIX_before + market_performance  + Selling.and.Marketing + Net.Income.Margin + RevGrowth + Total.Assets + log(Proceeds) + Type.of.Security  + Selling.and.Marketing:RevGrowth + market_performance:Selling.and.Marketing, family=binomial(link='logit'))
  
  y_pred = predict(logit.model_0_cv, newdata = test_list[[i]], type = "response")
  y_pred = as.numeric(y_pred>0.5)
  y_true = test_list[[i]]$Underpriced
  logit.model_0_auc  = AUC(y_pred = y_pred, y_true = y_true)
}
test_auc_0<-c(mean(logit.model_0_auc))
test_auc_0

```

##RF
```{r}
ipos.clean$Underpriced = ifelse(ipos.clean$LogOneDayChange >0.1823 , 1,0)
set.seed(123)
trainIndex <- createDataPartition(ipos.clean$Underpriced, p = .8, 
                                  list = FALSE, 
                                  times = 1)

train = ipos.clean[trainIndex,]
train = train %>%
  dplyr::select(-LogOneDayChange)
test = ipos.clean[-trainIndex,]
test = test %>%
  dplyr::select(-LogOneDayChange)

x_test = test %>%
  dplyr::select(-Underpriced)

rf_class <- randomForest(
  Underpriced ~ .,
  data=train,
  xtest = x_test,
  ytest = test$Underpriced,
  keep.forest=TRUE
)

pdata_rf <- predict(rf_class, newdata = test, type = "response")

confusionMatrix(data = as.factor(as.numeric(pdata_rf>0.5)), reference = as.factor(test$Underpriced))


```


