---
title: "R Notebook"
output: html_notebook
---

##LOAD
```{r}
library(quantmod)
library(finreportr)
library(edgar)
library(BatchGetSymbols)
library(lubridate)

library(pdftools)
library(glue)
library(tidyverse)

library(mice)

library(randomForest)
require(caTools)

library(car)
```


## Data Clean
```{r}

ipos.df = read.csv("MT IPO DATA_with_market_final.csv")

ipos.df$Net.Income.Margin = ipos.df$Net.Income / ipos.df$Total.Revenues.Last.Reported
ipos.df$OneDayChange = ipos.df$FirstDayClose/ipos.df$Offer.Price -1
ipos.df$LogOneDayChange = log(ipos.df$FirstDayClose/ipos.df$Offer.Price)
ipos.df$RevGrowth = ipos.df$Total.Revenues.Last.Reported/ipos.df$Total.Revenues.in.Previous.Year-1
ipos.df$Long.Term.Debt.to.Total.Asset.Ratio = ipos.df$Long.Term.Debt/ipos.df$Total.Assets
ipos.df$Total.VC.Funding.Raised = as.numeric(ipos.df$Total.VC.Funding.Raised)/1000



ipos = ipos.df %>% 
  dplyr::select(LogOneDayChange, VIX_before, market_performance,Total.VC.Funding.Raised, Total.Revenues.Last.Reported, Total.Assets,Long.Term.Debt, Long.Term.Debt.to.Total.Asset.Ratio, Selling.and.Marketing, Total.Operating.Expenses, Net.Income, Net.Income.Margin, Type.of.Security, Investment.Bank..Lead.Left., Additional.Lead.Underwriters, RevGrowth, Proceeds)

miceIPO <- mice(ipos, method="rf")  # perform mice imputation, based on random forests.
miceOutput <- complete(miceIPO)  # generate the completed data.

ipos.clean = miceOutput



```

##EDA
```{r}

ggplot(ipos.clean, aes(x= Total.Revenues.Last.Reported)) + geom_histogram(binwidth=100, colour="black", aes(y=..density.., fill=..count..), position = "stack") + theme_minimal()
ggplot(ipos.clean, aes(x= Selling.and.Marketing)) + geom_histogram(binwidth=10, colour="black", aes(y=..density.., fill=..count..), position = "stack") + theme_minimal()
ggplot(ipos.clean, aes(x= Proceeds)) + geom_histogram(binwidth=50, colour="black", aes(y=..density.., fill=..count..), position = "stack") + theme_minimal()
ggplot(ipos.clean, aes(x= Net.Income)) + geom_histogram(binwidth=40, colour="black", aes(y=..density.., fill=..count..), position = "stack") + theme_minimal()
ggplot(ipos.clean, aes(x= Net.Income.Margin)) + geom_histogram(binwidth=0.2, colour="black", aes(y=..density.., fill=..count..), position = "stack") + theme_minimal()


ggplot(ipos.clean, aes(x= LogOneDayChange)) + geom_histogram(binwidth=0.1, colour="black", aes(y=..density.., fill=..count..), position = "stack") + theme_minimal()

ipos.clean$Long.Term.Debt.Binary = ifelse(ipos.clean$Long.Term.Debt > 1, 1, 0)


```

##Regression
#TODO: check: smoothing functions
#TODO: Add industry stuff?
#TODO: Classification (return positive or neg)

#TODO: FORWARD OR BACKWARD SELECTION, STEP FUNCTION
```{r}
library(MASS)
# Fit the full model 
full.model <- lm(LogOneDayChange ~., data = ipos.clean)
# Stepwise regression model
step.model <- stepAIC(full.model, direction = "both", 
                      trace = FALSE)
summary(step.model)
```


## REGRESSION
```{r}
library(mgcv)

gam <- gam(data = ipos.clean, formula =  LogOneDayChange ~ s(VIX_before) + s(market_performance) + s(Total.Revenues.Last.Reported) + s(Total.Assets) + s(Selling.and.Marketing) + s(Net.Income) + s(Net.Income.Margin) + s(RevGrowth) + s(Total.VC.Funding.Raised) +s(Long.Term.Debt) +s(Proceeds) + Investment.Bank..Lead.Left.)

plot(gam, shade = TRUE)
summary(gam)

model.1 = lm(data = ipos.clean, formula = LogOneDayChange ~ VIX_before + market_performance + log(Total.Revenues.Last.Reported) + log(Total.Assets) + log(Selling.and.Marketing) + Net.Income + Net.Income.Margin + RevGrowth + log(Total.VC.Funding.Raised) + Long.Term.Debt + Total.Assets + log(Proceeds) + market_performance:Total.Revenues.Last.Reported + market_performance:Long.Term.Debt + Total.Assets:Selling.and.Marketing + Selling.and.Marketing:RevGrowth + Selling.and.Marketing:Total.VC.Funding.Raised)
summary(model.1)

vif(model.1)

par(mfrow=c(2,2))
plot(model.1)

```

##RF
```{r}
set.seed(123)
sample = sample.split(ipos.clean$LogOneDayChange, SplitRatio = .8)
train = subset(ipos.clean, sample == TRUE)
test  = subset(ipos.clean, sample == FALSE)

x_test = test %>%
  dplyr::select(-LogOneDayChange)

rf <- randomForest(
  LogOneDayChange ~ .,
  data=train,
  xtest = x_test,
  ytest = test$LogOneDayChange
)

oob <- sqrt(rf$mse)
validation <- sqrt(rf$test$mse)

tibble::tibble(
  `Out of Bag Error` = oob,
  `Test error` = validation,
  ntrees = 1:rf$ntree
) %>%
  gather(Metric, RMSE, -ntrees) %>%
  ggplot(aes(ntrees, RMSE, color = Metric)) +
  geom_line() +
  scale_y_continuous(labels = scales::dollar) +
  xlab("Number of trees")

varImpPlot(rf,type=2)

```

##Sentiment Analysis
```{r}

summary(ipos.clean)

```