---
output:
  pdf_document: default
  html_document: default
---
# Introduction {#intro}

This study aimed to investigate underpricing in venture-backed tech IPOs in the US after the 2008 financial crisis. The precise period investigated is 2009-2020. This paper sought to make the following unique contributions to this field of study: first, demonstrating the usefulness of using advanced statistical techniques to analyze IPO data, in contrast to most of the historical literature which relied on classical techniques such as linear regression; second, while most of the historical literature has focused on IPOs of a certain time period or in a certain geographic region, this paper seeks to analyze a unique set of IPOs with differentiating characteristics that there is limited literature about: venture-backed tech IPOs; and third, to investigate if particular investment banks or venture capital firms being associated with the IPO/company had any effect on underpricing – much of the historical literature has focused on market or firm factors instead of placing more of a focus on the investment banks and venture capital firms.

The current venture-backed startup landscape is awash with activity. There has been much media coverage of large Initial Public Offerings (e.g. Uber’s \$82 billion valuation at IPO, Lyft’s \$22 billion valuation at IPO, Slack’s $23 billion valuation at IPO), much talk of overvaluation (e.g. Uber, Lyft, and Slack stocks all suffering decreases in market capitalization post-IPO), and the raising of many multibillion venture funds dedicated to catalyzing and sustaining the growth of startups towards a profitable exit, such as an IPO. In 2018, there were 134 IPOs, 66% of which were VC-backed and 38 of which were tech IPOs. In 2018, tech IPOs generated almost \$12 billion in proceeds, but only 16% of those companies were profitable at time of IPO. The median market price to sales ratio for 2018 IPOs was at its highest mark since 2002 at 11.3 (Ritter 2018). These macro trends have been in play for around a decade, ever since the world recovered from the financial crisis of 2008.

Within this explosion activity are many factors and topics of discussion. The strategic focus of many technology startups has been placed on pursuing growth at all costs. Growth is often prioritized over profitability, leading to much criticism and many claims of overvaluation, especially as previously private startups seek funding in public markets, which have a much greater degree of scrutiny. Startups tend to IPO for a variety of reasons. A startup may seek to tap the public markets for financing, especially if the private markets become a less accessible source of capital for any reason. IPOs also provide an exit opportunity for early-stage investors and employees, allowing them to cash out on any equity they may own in the company. In these IPOs, although the theoretical goal of the issuance is to establish a fair price reflecting the true value of the company, there do exists incentives to underprice or overprice the issuance. Overpricing naturally means that more money will be raised upfront through the IPO (because it will be raised at a higher valuation). Underpricing allows for the possibility of a post-IPO “pop” in the share price, which attracts great PR and increased investor interest for the future. 

Much has been made of the phenomenon of underpricing, in which issuers can be seen to be “leaving money on the table” – with an underpriced IPO, a company is not raising as much money as it could be. Definitionally, an IPO is underpriced when there is an increase in stock value from the initial offering price to the first-day closing price. This one-day increase is often called an IPO “pop.” An IPO “pop” indicates that investors were actually willing to pay a higher price than the official IPO offer price. If the IPO had originally been offered at that higher price, then the startup would have raised more dollars. Ritter and Welch (2018) IPOs of US companies were underpriced by an average of 18 percent from 1980-2017 – at the height of the 2000 dot-com bubble, underpricing rose to extreme levels, and the average IPO was underpriced by over 70%.

Venture capitalists who back companies looking to IPO have expressed discontent over this phenomenon. Notably, Bill Gurley of Benchmark accuses the investment banks who run the IPO processes of consistently underpricing IPOs, leading to a cumulative $170bn left on the table for issuers.  

Investment banks play a key role in the IPO process – they have responsibilities in making sure that the issuer meets all the regulatory and  logistical requirements for IPO, and arguably more importantly, setting an IPO price and then allocating all the shares being offered at that price. They also collect fees (usually ~7%, known as the spread) for IPO’s that they underwrite. The size of spread depends both on negotiations between the underwriters and the issuers as well as amount of risk the underwriters take on (i.e. number of shares they decide to allocate). Generally, this spread is broken down 20%/20%/60% between management fee, underwriting fee, and selling concession (Torstila 2001).

These fees usually come in the form of the bank being able to purchase the issuer’s shares at a small discount to the price that will be offered to the public (Public Offering Price, or POP). This margin between the price that the bank can buy at and that the public can buy at is effectively the fee that the banks get paid. One of the primary determinants for the amount of fees that the banks make is the amount  
This paper sought to explore IPO underpricing with a focus on the role of these investment banks by seeing if any market or firm-specific factors were significant predictors of underpricing.
